### ISSUE TITLE
General CSS Styling Checklist

### ISSUE THREAD

**Issue by thinhgvo** [thinhgvo/fa23-cse110-lab3#1]
- [ ] Elements Color
- [ ] Comment
- [ ] Background color
- [ ] Unit:
    - [ ] 3 unique relative units
    - [ ] 3 unique absolute units
- [ ] Box Model:
    - [ ] Margins:
        - [ ] Long
        - [ ] Short
        - [ ] Auto margins
    - [ ] Padding:
        - [ ] Long
        - [ ] Short
    - [ ] Borders:
        - [ ] Border-style
        - [ ] Border-color
        - [ ] Border-width
        - [ ] Border-radius
- [ ] Text:
    - [ ] color
    - [ ] text-decoration
    - [ ] text-align
- [ ] Display:
    - [ ] None, block, inline-block, inline (Select 2) Apply these to the display properties
- [ ] Sizing:
    - [ ] Height
    - [ ] Width
    - [ ] Max-width
    - [ ] Min-width
- [ ] Position:
    - [ ] Static, relative, fixed, absolute, sticky (Apply these to the position properties)
- [ ] Pseudo-class
    - [ ] :hover
    - [ ] :active
- [ ] Layouts:
    - [ ] Flexbox:
        - [ ] Apply flex to display property
        - [ ] Must have more than two children within the element that is using Flexbox. Must use a minimum of three of the flexbox-related attributes
    - [ ] Grid:
        - [ ] Apply grid to display property
        - [ ] Must have more than two children within the element that is using Grid. Must use a minimum of three of the grid-related attributes
- [ ] Responsiveness:
    - [ ] At least one query based on the screen width
- [ ] Fonts:
    - [ ] Load a 3rd party font in either CSS or HTML.
